### ISSUE TITLE
Answers for questions can be reverted and correct answer is visible

### ISSUE THREAD

**Issue by pcvolkmer** [thm-projects/arsnova-backend#18]
Using ARSnova everyone is able to give the correct answer to questions within a session.

This issue seems not to be related to arsnova-backend only. Some architecture changes in arsnova-mobile and arsnova-backend are required.

By copying body of HTTP POST request with the current answer everyone is able to revert given answers and even show up correct anwers.

This can be done by following 5 simple steps. All you need is something like Firebug or Safari web developer tools and a REST client.

1. Start answering a question and copy the POST request body. Choose a wrong answer. if you go back to the answered question, you can see, that you are not able to answer this question any more.
![arsnova2](https://cloud.githubusercontent.com/assets/5081579/8766225/5efba6ba-2e2f-11e5-93e0-f410e784710f.png)

2. Replace JSON-part "answerText" of the answer request with something else e.g. "fail"

3. Remember each URI of the answer POST requests and send a new request with the modified body

4. Go back to session page and re enter questions

5. You will see questions with the correct answer marked
![arsnova](https://cloud.githubusercontent.com/assets/5081579/8766209/d6f50b58-2e2e-11e5-8b09-751a0a26dc15.png)

You could try to mark an other answer. But this will fail. Only the correct answer will be shown.

If you do the same steps and modify each answers POST request to contain the text of the correct answer, you even have stored your correct answers.
![arsnova1](https://cloud.githubusercontent.com/assets/5081579/8766213/f58036ce-2e2e-11e5-9f09-c7b46893f0ac.png)

Not a big deal for self assessment, but if statistics about audience knowledge should be evaluated, it could matter.

**Comment by dgerhardt** [comment]
Aren't #18 and #19 the same issue, just for different question formats? I'm closing this one for now in favor of #19 so we can keep the discussion in one place.
