### ISSUE TITLE
Answers for mutliple choice questions can be reverted too

### ISSUE THREAD

**Issue by pcvolkmer** [thm-projects/arsnova-backend#19]
As described in #18 questions can be re answered and correct answers can be given at any point.

Same issue for MC question as used for question variant "preparation" in demo session. By following the simple steps in #18 anyone is able to revert and update his answers.

Simply change POST requests JSON object to have property "answerText" reflect an comma separated bit pattern of correct answers e.g. "0,1,1,0" (mark possible answers 2 and 3 as correct answers, 1 and 4 are incorrect answers).

**Comment by kqc-real** [comment]
We'd be very pleased to get a Pull Request from you on this issue.

**Comment by pcvolkmer** [comment]
These issues are not to be fixed very soon by my self. The handling of answers seems to be broken by design. A possible patch must ... :
* Ensure that one user can send only one request per answer. Therefore every answer has to be checked against database.
* Ensure that only answers could be send, that match one of the possible answers.
* In case of multiple choice questions, the answer pattern must reflect exactly the amount of possible answers. This is not given right now. An answer "0,2,3,1,0,0,0,2,7" will be accepted, even if there are only 4 possible answers. For given example it is equal to "0,0,0,1". Every answer containing an array of numbers will be accepted without sending some kind of HTTP 4xx Error code. 

Some more points to be figured out:
* If possible answers list should be mixed up for every user, the solution of one static answer pattern seems to be a bad idea. In my opinion, a much better solution would be: Any possible answer gets a unique ID (question ID given from CouchDB and number of possible answer e.g. a3567....4711_0 for the first -index 0- of possible answers). The client must send an array of selected IDs back to arsnova-backend. Some kind of checks can be done by extracting question ID and index of possible answers.
* Same solution could be used to implement single choice answers. Here, only one answer ID will be send to server.

A solution for these issues could not be found without being coordinated by ARSnova core team. Any patches I could provide will change behaviour of backend and will cause changes to be made in frontend.

**Comment by dgerhardt** [comment]
Thanks for the report!

The following ideas are not directly related to this issue. Could you report them to #22 instead?
> * Ensure that only answers could be send, that match one of the possible answers.
> * In case of multiple choice questions, the answer pattern must reflect exactly the amount of possible answers. This is not given right now. An answer "0,2,3,1,0,0,0,2,7" will be accepted, even if there are only 4 possible answers. For given example, it is equal to "0,0,0,1". Every answer containing an array of numbers will be accepted without sending some kind of HTTP 4xx Error code.
