### ISSUE TITLE
Correct answer provided by API in question response

### ISSUE THREAD

**Issue by pcvolkmer** [thm-projects/arsnova-backend#20]
It is possible to get the correct answer just by doing a simple response analysis of question request.

Simple steps to be done:
1. Request some questions e.g. `https://arsnova.eu/api/lecturerquestion/?sessionkey=71073692`
2. Take a look at `possibleAnswers` property.
3. Send requests with correct answers by using requests described in #18. 

Example response part:

``` javascript
    ....
    "possibleAnswers":
        [
            {
                "id": "A",
                "text": "A: Ampère's circuital law",
                "correct": false,
                "value": -10
            },
            {
                "id": "B",
                "text": "B: Maxwell-Faraday equation",
                "correct": true,
                "value": 10
            },
            {
                "id": "C",
                "text": "C: Gauss's law for magnetism",
                "correct": false,
                "value": -10
            }
        ],
    ...
```

If questions are MC questions, use requests described in #19

**Comment by dgerhardt** [comment]
Thanks for reporting this. Unfortunately, this isn't fixable without breaking changes to the API.
