### ISSUE TITLE
Answer counter counts up un repeated answers on same question by same user

### ISSUE THREAD

**Issue by pcvolkmer** [thm-projects/arsnova-backend#21]
Using requests described in #18 and #19 the answer counter (yellow badge) counts up each repeated answer for same user. It is possible to reach 1M+ answers just by running a script for several minutes.

**Comment by dgerhardt** [comment]
We can't easily fix this specific issue since a user could create multiple accounts to achieve a similar effect. But it would make sense to limit POST and PUT request accepted in a time span in general.
