### ISSUE TITLE
Answers are not checked against range of values

### ISSUE THREAD

**Issue by pcvolkmer** [thm-projects/arsnova-backend#22]
Answering question images it is possible to set marks outside of given image.

Simple steps to take when logged in to ARSnova and visiting Demo session _71 07 36 92_:
1. Send POST request to `https://arsnova.eu/api/lecturerquestion/c68ec1be7e16b0dfb64a419b2a32b5d7/answer/` containing the request body `{"answerText":"-1;-1,1;-1,0;0,10;0,11;0,12;0,13;0,14;0,14;9"}`. Marks on (-1;-1), (1;-1), (14;0), (14;9) are not within image!
2. Go back to session page
3. Visit lecturer question page and visit question _5_

You should see something like this:
![arsnova3](https://cloud.githubusercontent.com/assets/5081579/9025572/1241abea-390a-11e5-97b2-e1790fe008bb.png)

**Comment by dgerhardt** [comment]
Thank you for reporting this. I've edited the title since it applies to all question formats.
