### ISSUE TITLE
Security issue in guest login

### ISSUE THREAD

**Issue by pcvolkmer** [thm-projects/arsnova-backend#24]
It is possible to change current guest user ID by sending a simple HTTP-GET request
    https://arsnova.eu/api/auth/login?user=Guest1234567890&type=guest
just when using ARSnova.

To check if the request succeeds you can send another request
    https://arsnova.eu/api/whoami

The response should be something like

```
{"username":"Guest1234567890","type":"guest","role":null}
```

You are the guest user with ID `Guest1234567890` right now! Since guest users are not banned with

```
userService.increaseFailedLoginCount();
```

anyone is able to brute force available guest logins and change answers which might change statistic values within any ARSnova sessions opened to all audience.

Some simple solution could combine guest login changes with failed login count.

**Comment by dgerhardt** [comment]
Thanks for your report.

> Some simple solution could combine guest login changes with failed login count.

Unfortunately this wouldn't work for guest logins since the bans are based on IP addresses. It would render guest logins useless from university networks since all users have the same address.

**Comment by dgerhardt** [comment]
The only way I see to prevent this issue is the use of CAPTCHAs but they are cumbersome. A solution could be a soft limit for guest logins after which CAPTCHAs are enforced. But a reasonable limit with university networks in mind (~500) would still allow malicious users to manipulate statistics.

**Comment by Rillke** [comment]
Perhaps rename this issue to: `Guest sessions prone to bruteforce attacks`?
