### ISSUE TITLE
Statistics did not count online users

### ISSUE THREAD

**Issue by pcvolkmer** [thm-projects/arsnova-backend#25]
As a user I can use ARSnova, visit a session and answer questions without being counted as online user in statistics table.

Same statistics data will be shown in blogs landing page.

![arsnova](https://cloud.githubusercontent.com/assets/5081579/9288048/f5b3b732-4333-11e5-9829-969368fc090f.png)

**Comment by dgerhardt** [comment]
I can't reproduce this. The statistics work as intended for me. As soon as I join a session, the counter on the blog increases. When I leave the session, it decreases.

Could you please make sure that the Websocket connection is working for you when the problem occurs by switching multiple times between the four feedback options?

Besides, the statistics panel has to be reopened. It doesn't update in real-time.

**Comment by pcvolkmer** [comment]
It seems installation on arsnova.thm.de is broken. I have tested this installation instead of arsnova.eu.

**Comment by dgerhardt** [comment]
I can't reproduce this on arsnova.thm.de either. I've tested session joining and statistics with FF, Chromium and Chrome. Which brower do you use?

**Comment by pcvolkmer** [comment]
Firefox 40.0 on a Linux system.
By the way: Using Firefox mobile 40 on Android does not show any statistics at all. But this seems to be an issue in ARSnova-mobile and will be reported there.

![screenshot_2015-08-15-11-00-36](https://cloud.githubusercontent.com/assets/5081579/9288245/1b3b2162-433d-11e5-9733-d366303f80ed.png)

**Comment by pcvolkmer** [comment]
After a few years I tried to reproduce this error. It's either the newer Firefox Mobile 6, changes in ARSnova or both, but the problem no longer occurs
