### ISSUE TITLE
Apache config

### ISSUE THREAD

**Issue by V3ndetta** [thm-projects/arsnova-backend#3]
By default, a simple 

```
    <Location />
    ProxyPass ajp://127.0.0.1:8009/
    ProxyPassReverse ajp://127.0.0.1:8009/
    </Location>
```

as given in documentation won't work at all.

You need at least 

```
 Redirect /id https://YOUR.DOMAIN.COM/#id
```

to get all Apple stuff working.

In addition you need to rewrite all /resources/ requests to /arsnova/resources/ by default to load all btn_*.png

**Comment by Rillke** [comment]
Perhaps omit setting up Apache at all and make Tomcat serve everything?
