### ISSUE TITLE
[SECURITY] Guest login possible in spite of being disabled for a role

### ISSUE THREAD

**Issue by Rillke** [thm-projects/arsnova-backend#35]
Steps to reproduce:
- Go to https://arsnova.thm.de
- Confirm banner message, click "Dozent/in"
- Click "ARSnova"
- Open https://arsnova.thm.de/api/auth/login?type=guest in a new tab
- Press the back button in the tab which shows the ARSnova login screen
- You are now logged in as guest and can create sessions and do other activities your admin didn't want you to

**Comment by Rillke** [comment]
List of auth methods and their allowed roles: https://arsnova.thm.de/api/auth/services

**Comment by Rillke** [comment]
When you fix the underlying issues, please cite `Rillke at Wikimedia` for reporting.

**Comment by dgerhardt** [comment]
Thank you for reporting this issue. We are in the process of releasing version 2.4.1 which fixes the handling of disabled authentication services (regardless of roles).

Currently, the backend does not differentiate between roles outside of sessions. Unfortunately, that means there is no simple fix for this issue and we have to defer it until a later release. For now I think, the best solution is to document this behavoir in the configuration file.

**Comment by dgerhardt** [comment]
As of 2.4.1 this behavior is properly documented.
