### ISSUE TITLE
[SECURITY] Missing CSRF tokens, CORS headers present

### ISSUE THREAD

**Issue by Rillke** [thm-projects/arsnova-backend#37]
In account management, the CSRF token system is entirely missing. This allows any website to make its visitors registering and creating sessions; additionally CORS headers are present that allow any website to make its visitors create a session, read the session key and thus create questions.

Demo for the last case. I guess there are more vulnerabilities so more will follow: https://jsfiddle.net/Lvr1xvm9/6/

**Comment by Rillke** [comment]
User session hijacking: https://jsfiddle.net/xngj6gh2/3/

**Comment by Rillke** [comment]
Since it is possible to steal the user name from any ARSnova instance, this also badly impacts privacy. 

When you fix the underlying issues, please cite `Rillke at Wikimedia` for reporting.

**Comment by dgerhardt** [comment]
Thank you for reporting and demonstrating this issue. We are in the process of releasing new versions fixing the CORS implementation.

There are currently no plans to implement CSRF tokens. The ARSnova REST API does not allow resource manipulation via [simple methods](https://www.w3.org/TR/cors/#simple-method) so it is not vulnerable to CSRF (assuming the browsers's CORS implementations are solid). The use of CSRF tokens would limit the legitimate use of the API from trusted origins.

**Comment by Rillke** [comment]
> The ARSnova REST API does not allow resource manipulation via simple methods

Do you consider creating sessions being resource manipulation?

**Comment by dgerhardt** [comment]
> Do you consider creating sessions being resource manipulation?

Yes, I do. Do you still see a way to do so using cross origin requests?

**Comment by Rillke** [comment]
> Yes, I do. Do you still see a way to do so using cross origin requests?

If really only non-simple methods are being used, it should be as secure as described in https://stackoverflow.com/a/11972282/2683737 - due to the preflight request (OPTIONS) that the browser won't evaluate. You're using Spring framework, so make sure that `HiddenHttpMethodFilter` is not and can't be easily enabled by accident, or only with CSRF tokens.

-----
A word on simple methods:

You can POST or GET to any origin if no constraint is set by the CSP [caveat: CSP [might not be implemented by all browsers](http://caniuse.com/#feat=contentsecuritypolicy) currently in use and might cause other side effects].

The response is not readable by the client if no matching CORS headers are set. For creating sessions, this doesn't matter as no token only known to the site running ARSnova is required for the request to succeed, thus any other site can make their visitors sending POSTs and ARSnova backend would normally process it.

**Comment by dgerhardt** [comment]
2.4.1, 2.3.3 and 2.2.2 have been released which fix the CORS implementation and allow to set trusted origins. CORS headers are no longer sent in 2.1.2 and 2.0.4.

> You can POST or GET to any origin if no constraint is set by the CSP

When a `Content-Type: application/json` header is set, POST requests are no longer considered "simple". With a few exceptions for user management the backend only handles `application/json` so a preflight request will be sent.
