### ISSUE TITLE
No LDAP Auth

### ISSUE THREAD

**Issue by V3ndetta** [thm-projects/arsnova-backend#4]
There is no documentation nor an configuration example how to get LDAP to work. Only CAS, Facebook, Twitter and Google are allowed/needed.

**Comment by Rillke** [comment]
My LDAP config looks like this:

```
# The context paths where the ARSnova modules have been deployed
customization.path=/bbiz
...
# LDAP authentication
#
# Specific parameters:
# url: LDAP server URL
# user-dn-pattern: Pattern used to check user credentials against the LDAP
#     server. {0} will be replaced with the user ID by ARSnova.
#
security.ldap.enabled=true
security.ldap.allowed-roles=speaker,student
security.ldap.title=My big biz
security.ldap.login-dialog-path=login-ldap.html
security.ldap.image=btn_bbiz
security.ldap.order=2
security.ldap.url=ldaps://ldap.bigbiz.example.com:636/o=bbiz,c=com
security.ldap.user-dn-pattern=uid={0},ou=arsnova
```

Under arsnova.bigbiz.example.com/bbiz/login-ldap.html is a page similar to [the ARSnova EU login page](https://arsnova.eu/thm/account.html?redirect=%2Fmobile%2F); just replace `var type = "arsnova";` with `var type = "ldap";`

Note that you should not keep your server logs or you must mutilate them due to #36

**Comment by mocsap** [comment]
Will ARSnova work together with Windows Active Directory? I'm not able to get it into work using LDAP. My LDAP configuration section looks like this:

security.ldap.enabled=true
security.ldap.allowed-roles=speaker,student
security.ldap.title=LDAP-Auth
security.ldap.login-dialog-path=login-ldap.html
security.ldap.image=logo_ldap
security.ldap.order=2
security.ldap.url=ldap://ad.example.com:389/dc=ad,dc=example.com
security.ldap.user-dn-pattern=sAMAccountname={0}

I'm constantly getting the 401 error - "User not authorized". Does any of you have some experience in this field?

**Comment by dgerhardt** [comment]
We haven't tested ARSnova's LDAP support against AD yet but since AD doesn't add any additional requirements for LDAP clients it should work.

Since your issue isn't directly related to the original topic, please create a new one for further discussion.
