### ISSUE TITLE
SAML2 Auth

### ISSUE THREAD

**Issue by symptog** [thm-projects/arsnova-backend#43]
Is there a possibility to integrate SAML2 authentication?

**Comment by dgerhardt** [comment]
The framework we are using for authentication (Spring Security) does have support for SAML 2.0 so it should be possible.

See http://projects.spring.io/spring-security-saml/.

**Comment by symptog** [comment]
Thank you.

Where should I start looking at in the code?

**Comment by dgerhardt** [comment]
Have a look at the LoginController:
https://github.com/thm-projects/arsnova-backend/blob/master/src/main/java/de/thm/arsnova/controller/LoginController.java#L147

You'll need to add the following Maven dependency:
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.springframework.security.extensions%22%20AND%20a%3A%22spring-security-saml2-core%22
