### ISSUE TITLE
ARSnova's LDAP Active Directory

### ISSUE THREAD

**Issue by mocsap** [thm-projects/arsnova-backend#46]
Will ARSnova work together with Windows Active Directory? I'm not able to get it into work using the LDAP interface. My configuration file looks like this:

security.ldap.enabled=true
security.ldap.allowed-roles=speaker,student
security.ldap.title=LDAP-Auth
security.ldap.login-dialog-path=login-ldap.html
security.ldap.image=logo_ldap
security.ldap.order=2
security.ldap.url=ldap://ad.example.com:389/dc=ad,dc=example.com
security.ldap.user-dn-pattern=sAMAccountname={0}

I have replaced the var type = "arsnova"; with var type = "ldap" under the login-ldap.html page. Unfortunately but I'm constantly getting the 401 error - "User not authorized". 

Does any of you have some experience in configuring Windows AD with ARSNova?

**Comment by dgerhardt** [comment]
This looks like the AD LDAP server isn't configured to allow anonymous binding. I suggest you test that LDAP authentication is working correctly using command line tools before setting up LDAP for ARSnova. You can test bind authentication using `ldapwhoami`:
```shell
ldapwhoami -v -H ldap://ad.example.com:389/dc=ad,dc=example.com -D "sAMAccountname=<replace-with-userid>" -W
```

**Comment by mocsap** [comment]
Thanks for this tip. The LDAP connection can be only established, when the following scheme is used:
ldapwhoami -v -H ldap://ad.example.com:389 -D "domain\user" -W

After providing the user LDAP password, I'm getting the "Result: Sucess (0)" as a connection status.

With -D "sAMAaccountname=<uid>" bind initialization error appears - "Invalid credentials (49). 

If I understand it correctly, the connection should be established after changing the: _security.ldap.user-dn-pattern_ in the configuration file. I have tried to make some changes of this option in the configuration file, however without any effects. Any advice?

**Comment by dgerhardt** [comment]
The Windows domain syntax isn't standard LDAP syntax for a DN and I can't tell if it will work with ARSnova. At least you would need to escape the backslash in the properties file.

Using `sAMAccountname=...` didn't work since `sAMAccountname` isn't part of the DN. AD uses the common name as part of the DN instead. This means, you can use simple bind authentication only if you want to use the users real name for authentication. To use sAMAccountname for authentication, you need to perform an LDAP search.
Additionally, `dc=example.com` doesn't look right. I think, the domain needs to be split into `dc=example,dc=com`.

**Comment by mocsap** [comment]
Dear @dgerhardt, thank you for sharing this. I have tried to establish the connection using following parameters:

security.ldap.url=ldap://username:password@ad.example.com:389
security.ldap.user-dn-pattern=

Using this connection string and the login form: https://arsnova.eu/thm/account.html?redirect=%2Fmobile%2F(url) I'm getting the Error 405: Method not allowed. 


> Allow | GET, HEAD
> -- | --
> Cache-Control | no-cache, no-store, max-age=0, must-revalidate
> Connection | Keep-Alive
> Content-Language | de
> Content-Length | 0
> Date | Fri, 28 Jul 2017 06:21:47 GMT
> Expires | 0
> Keep-Alive | timeout=5, max=100
> Pragma | no-cache
> Server | Apache/2.4.10 (Debian)
> Strict-Transport-Security | max-age=31536000
> X-Content-Type-Options | nosniff
> X-Frame-Options | DENY
> X-XSS-Protection | 1; mode=block

It looks that the server configuration don't accept the POST method which is included in the XMLHttpReqest(). However this is already off topic, therefore I will close this thread.
