### ISSUE TITLE
LDAP working, how to add another security.ldap.user-dn-pattern variable?

### ISSUE THREAD

**Issue by dmoses** [thm-projects/arsnova-backend#47]
Finally got LDAP using Active Directory working, but we have two DN - one for staff and one for students.  How can we add another dn? 

Here's an example for our arsnova.properties file:
security.ldap.user-dn-pattern=cn={0},ou=accounts,ou=staff,dc=adds,dc=ca

and I would like to add another so that students can log in ... 
security.ldap.user-dn-pattern=cn={0},ou=accounts,ou=staff,dc=adds,dc=ca
security.ldap.user-dn-pattern=cn={0},ou=accounts,ou=students,dc=adds,dc=ca

Is there a different method for adding another dn? 

Appreciate any help.

**Comment by dgerhardt** [comment]
You cannot use LDAP DN binding for authentication with ARSnova in this case. I suggest, you do an LDAP search instead which is more flexible. In this case, you need an additional LDAP user which is allowed to search the directory.

Your configuration could look like this:
# user-dn-pattern setting is disabled:
# security.ldap.user-dn-pattern=cn={0},ou=accounts,ou=staff,dc=adds,dc=ca
security.ldap.user-search-filter=(cn={0})
security.ldap.user-search-base="dc=adds,dc=ca"
security.ldap.manager-user-dn=cn=arsnova-manager,ou=ldapmanagers,dc=adds,dc=ca
security.ldap.manager-password=arsnova-manager-password

A list of all LDAP settings:
https://github.com/thm-projects/arsnova-backend/blob/2.5/src/main/resources/arsnova.properties.example#L128-L134

**Comment by dmoses** [comment]
Thank you. I'll test that option.
Donald

**Comment by dmoses** [comment]
That suggestion worked for me.
Thanks.

**Comment by mocsap** [comment]
I have exact the same situation, however in my case the connection between Active Directory and LDAP didn't work. I'm getting constantly an LDAP: error code 49 - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580.

The arsnova.properties:
> 
> security.ldap.user-search-filter=(sAMAccountName={0})
> security.ldap.user-search-base=dc=ad,dc=name,dc=de
> security.ldap.manager-user-dn=cn=arsnova-manager
> security.ldap.manager-password=arsnova-manager-password

The binding credentials are correct, as I'm able to send the request to ldap using ldapsearch. 

Appreciate for any suggestion!

**Comment by mocsap** [comment]
Hi, in the meantime I have tried to use everything what was possible, without finding any workaround. Maybe someone is able to help me further with the configuration of LDAP -> Windows AD issue? Anyone?
