### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by ktiu** [thm-projects/arsnova-backend#53]
For my use case I'm considering accessing the API directly in order to integrate student answers and feedback tightly into my (revealjs) presentation. Is there a doc of API calls / auth methods? Thank you!

**Comment by dgerhardt** [comment]
API docs are available at https://arsnova.thm.de/apidoc/.

**Comment by ktiu** [comment]
Great, thank you! Might it make sense to link this in arsnova-backend/src/site/markdown/development.md ?
