### ISSUE TITLE
LDAP Login: 404 page not found

### ISSUE THREAD

**Issue by sboeser** [thm-projects/arsnova-backend#56]
Dear developers,

we have tried to enable LDAP authentication for our ARSNova installation.  Guest authentication works fine, but once I click on the LDAP button, I get "404 - page not found".

The requested address is:
http://arsnova.our-domain.de/customization/login-ldap.html?redirect=%2Fmobile%2F

Is there any documentation on how to configure LDAP (and ARSNova in general)?

**Comment by tekay** [comment]
Hello,
for LDAP the login page (login-ldap.html) is not included in the arsnova-mobile project. We have another repository (https://github.com/thm-projects/arsnova-customization) which has a account.html file that can be used for ldap login. You need to change line 212 (var type = "ldap") and rename the file to `ldap-login.html`. It can be built with gradle to create a .war - file to deploy with tomcat8. You'll also need to configure your webserver to route to the customization.
Alternatively, you can just use the static html file and configure the webserver to use this.

For LDAP configuration there are variables (`security.ldap`) in the `arsnova.properties`.
Further installation documentation is found here: https://github.com/thm-projects/arsnova-backend/blob/master/src/site/markdown/installation.md ; the arsnova.properties - file is commented as well.

**Comment by sboeser** [comment]
Dear Tekay,

thank you very much for the response. Using a static html file, we have been able to communicate with the LDAP server. However, it seems that we do not have the right configuration yet to formulate the LDAP query correctly. Here is the error message:

```
17:57:28,665  INFO http-nio-127.0.0.1-8080-exec-10 controller.LoginController:215 - LDAP authentication failed.
org.springframework.security.authentication.InternalAuthenticationServiceException:
[LDAP: error code 32 - No Such Object]; nested exception is javax.naming.NameNotFoundException: 
[LDAP: error code 32 - No Such Object]; remaining name 'ou=people' at org.springframework.security.ldap.authentication.LdapAuthenticationProvider.doAuthentication(LdapAuthenticationProvider.java:206)
````
Our LDAP configuration in `arsnova.properties` looks like this

```
# Specific parameters:
# url: LDAP server URL
# user-dn-pattern: Pattern used to check user credentials against the LDAP
#     server. {0} will be replaced with the user ID by ARSnova.
#
security.ldap.enabled=true
security.ldap.allowed-roles=speaker,student
security.ldap.title=LDAP
security.ldap.login-dialog-path=login-ldap.html
security.ldap.image=
security.ldap.order=0
security.ldap.url=ldaps://ldap-01.zdv.uni-mainz.de:636/dc=uni-mainz.de,dc=de

#security.ldap.user-dn-pattern=uid={0},ou=staff,ou=people
#security.ldap.user-dn-pattern=uid={0},ou=people,dc=uni-mainz.de,dc=de"
# Set the following properties if you want to use LDAP search instead of binding
# with a DN pattern
security.ldap.user-search-filter=(uid={0})
security.ldap.user-search-base=ou=people
# Configure the LDAP manager user if anonymous binding is not allowed
#security.ldap.manager-user-dn=cn=arsnova-manager,dc=example,dc=com
#security.ldap.manager-password=arsnova
#security.ldap.cert=ca-zdv-ldap.pem
```
Thanks a lot!

**Comment by tekay** [comment]
Hello sboeser,
i'm not quiet sure how your ldap-server is configured. Do you want to use ldap bind or the search?
`security.ldap.url` only needs the url (without the `/dc=uni-[...]`), you can add the dc-parts to the `security.ldap.user-search-base`.
The error message indicates that the `security.ldap-user-search-base` seems to be wrong.

I hope that helps.
