### ISSUE TITLE
Unexpected Response-Header Arsnova-Api

### ISSUE THREAD

**Issue by Babofett** [thm-projects/arsnova-backend#67]
Requesting resources with an unmatching HTTP-Request Type should response with HTTP 405 - Method Not Allowed, instead of a 500 - Internal Error with JSON Response Body as I would not necessarily check the response body of a Post request. Both APIs arsnova.thm.de/api/statistics and https://arsnova.eu/api/statistics are having a hard time dealing with unfitting requests, though arsnova.thm.de seems to handle them a touch better. 
![bildschirmfoto von 2018-12-19 17-53-06](https://user-images.githubusercontent.com/46003718/50235273-cd504880-03b7-11e9-80c8-7ed7322e9e6a.png)
![bildschirmfoto von 2018-12-19 17-53-03](https://user-images.githubusercontent.com/46003718/50235540-697a4f80-03b8-11e9-945c-d5916bddedf3.png)

**Comment by dgerhardt** [comment]
Thank you for reporting this issue.
